### ISSUE TITLE
Enhancement Request: etr bonelink change

### ISSUE THREAD

**Issue by StardustZfighter** [LazyBone152/EEPKOrganiser#2]
changing the bonelink in etr by xml seems to make the game crash. So by having an option in etr edit to change the linked bones in eepkorganizer would really help

**Comment by LazyBone152** [comment]
This can't be done with the way the EEPK Organizer currently handles ETR files. It could only replace bone names with a bone of equal or less length.

Also please post issues on the main [repo ](https://github.com/LazyBone152/XV2-Tools/issues). This one is only for releases and I don't check it (I only happened to see it this time because I was posting a release).
